config/routes.rb
EnglishQuiz::Application.routes.draw do
  devise_for :users, :controllers =>{ :sessions => "users/sessions" }

  resources :quizzes do
    resources :questions
    resources :text_questions
    resources :dictation_questions
    resources :multiple_choice_questions    
  end
  
  resources :users do
    resources :statistics
    resources :practice_entries
  end
  
  resources :tags
  
  root :to => "home#index"
  match '/quizzes/tags/:tag' => "quizzes#index", :as => :quiz_tag
  match '/quizzes/:id/reassign' => "quizzes#reassign", :as => :reassign_question
  match '/questions/:id/edit' => "questions#edit", :as => :edit_question  
  match "/multiple_choice_questions/:id" => "multiple_choice_questions#show", :as => :multiple_choice_question, :via => :get
  match "/multiple_choice_questions/:id" => "multiple_choice_questions#update", :via => :put
  match 'statistics' => "statistics#create"
  match '/quizzes/:id/take' => "quizzes#take", :as => :take
  match "/quizzes/:quiz_id/questions/new" => "patients#show"
  match "/images/uploads/*path" => "gridfs#serve"
  
  resources :practice_entries
  

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  inherit_resources
  load_and_authorize_resource
  before_filter :authenticate_user!, :except => :show
  respond_to :html, :xml
  actions :index, :create, :edit, :update, :show
  def index
    @tags = Tag.where(:type => :quiz).group_by(&:name)
    @quizzes = Quiz.tag_search(params[:tag])
    #index!
  end
  def edit
    @quiz = Quiz.find(params[:id])
    @tag = Tag.new
    @question = MultipleChoiceQuestion.new
    
    4.times { @question.choices.new }
    #@new_quiz = Quiz.new
    #@new_quiz.questions =MultipleChoiceQuestion.new]
  end
  def create
    create! { new_quiz_question_url(@quiz) }
  end
  def update
    update! { quizzes_path }
  end
  def take
    @quiz = Quiz.find(params[:id])
  end
  def reassign
    # Only reassign if questions were selected
    unless params[:assignees].blank?
      # Quiz that is gaining the questions
      receiving_quiz = Quiz.where(:number => params[:receiving_id]).first
      unless receiving_quiz.nil?
        # Grab question id's from assign parameters and reassign their quiz id.
        params[:assignees].each do |question_id|
          question = Question.find(question_id)
          question.quiz = receiving_quiz
          question.save!
        end
        flash[:notice] = params[:assignees].count.to_s + " questions reassigned successfully."
        # redirect to quiz that received all the questions
        redirect_to quiz_url(receiving_quiz)
      else
        flash[:alert] = "You must enter a quiz ID for reassignment."
        redirect_to quiz_url(params[:id])
      end
    else
      flash[:alert] = "You must select at least one question to reassign."
      redirect_to quiz_url(params[:id])
    end
  end  
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/edit.html.haml
.header
  %h2 Editing #{@quiz.title }

.content
  = simple_form_for @quiz do |f|
    = f.input :title
    %br/
    = f.submit :class => "green-rounded"
    
  %br/
  %h4 Tags:
  .tag-container
    #tags
      - @quiz.tags.each do |tag|
        = link_to tag_path(tag), :method => :delete, :remote => true, :class => "tag_link" do
          .rounded-tag{:id => "tag_#{tag.id}"}
            = tag.name
            .delete-link x
    .clear

  %br/
  %h4 New Tag:
  = simple_form_for @tag, :html => {:class => "hello"}, :remote => true do |f|
    = f.input :name
    = hidden_field_tag :taggable_id, @quiz.id
    = hidden_field_tag :taggable_type, @quiz.class.to_s
    %br/
    = f.submit "Add Tag", :class => "green-rounded"

:javascript
  $('#new_tag').bind('ajax:success', function(evt, data, status, xhr) {
    tag_html = $(xhr.responseText);
    tag_html.hide();
    $('#tags').append(tag_html);
    tag_html.fadeIn();
    $('#tag_name').val("");

    tag_html.mouseover(function() {
      // Show delete icon
      $(this).find('.delete-link').show();
    });

    tag_html.mouseout(function() {
      $(this).find('.delete-link').hide();
    });

    $(tag_html).bind('ajax:success', function(evt, data, status, xhr) {    
      $('#'+xhr.responseText).fadeOut();
    });

  });

  $('a.tag_link').bind('ajax:success', function(evt, data, status, xhr) {    
    $('#'+xhr.responseText).fadeOut();
  });

  $(document).ready(function(){
    $('.rounded-tag').mouseover(function() {
      // Show delete icon
      $(this).find('.delete-link').show();
    });

    $('.rounded-tag').mouseout(function() {
      $(this).find('.delete-link').hide();
    });

  });

app/views/quizzes/index.html.haml
.header
  %h2 Manage Quizzes
  
.content
  %table.big{:style => "float: left; width: 830px;"}
    %tr
      %th Title
      %th Number of Questions
      %th Actions
      %th Unique ID

    = render :partial => '/shared/quiz_row', :collection => @quizzes, :as => :quiz
  .tag-cloud
    %h4 Tag Cloud
    .tag-container
      - @tags.each do |tag_array|
        = link_to quiz_tag_path(tag_array[0]) do
          .rounded-tag= tag_array[0]
      .clear

  .clear
    
  = simple_form_for Quiz.new do |f|
    = f.input :title
    = f.submit "Create New Quiz", :class => "green-rounded"

app/views/quizzes/show.html.haml
.header
  %h2 #{@quiz.title } summary

.content
  = simple_form_for @quiz, :url => :reassign_question do |f|
    - if current_user.admin?
      Re-assign questions to
      = text_field_tag :receiving_id, '' , :style => "width: 50px;"
      = f.submit "Reassign"
    %table#questions-table.big
      %thead
        %tr
          %th
          %th Title
          %th Audio
          %th Image
          %th Question Type
          %th
      %tbody
        = render :partial => '/shared/admin_question_row', :collection => @quiz.questions, :as => :question


  - if current_user.admin?
    .green-rounded= link_to "Add Questions", new_quiz_question_url(@quiz)
  .green-rounded= link_to "Take Quiz", take_url(@quiz)

:javascript
  $('#questions-table input').click(function() {
       $(this).parent().parent().toggleClass('highlight');
  });

app/views/quizzes/show.xml.haml
!!! XML
%quiz
  %title= @quiz.title
  %id= @quiz.id
  %questions
    - @quiz.questions.each do |question|
      - if question.class.to_s == Question::MULTIPLE_CHOICE
        - type = (question.multiple_response?) ? "MultipleAnswerQuestion" : Question::MULTIPLE_CHOICE
      - else
        - type = question.class.to_s
      %question{:type => type}
        %title= question.title
        %audio= question.audio.url
        %image= question.image.url
        - if question.class.to_s == Question::DICTATION or question.class.to_s == Question::TEXT
          %answer= question.answer
          
        - if question.class.to_s == Question::MULTIPLE_CHOICE
          %choices
            - question.choices.each do |choice|
              %choice
                %id= choice.id
                %question= choice.question
                %correct= choice.correct

app/views/quizzes/take.html.haml
.header
  %h2 Taking Quiz #{ @quiz.title }
  
.content
  #flashplayer{:style => "width: 720px; margin: auto;"}
:javascript
  $(document).ready(function() {    
    $('#flashplayer').flash({
        src: "/quiz.v1.3.2.swf?QuizId=#{@quiz.id}&UserId=#{current_user.id}",
        width: "720",
        height: "580",
        allowscriptaccess: "always"
    });
  });