config/routes.rb
EnglishQuiz::Application.routes.draw do
  devise_for :users, :controllers =>{ :sessions => "users/sessions" }

  resources :quizzes do
    resources :questions
    resources :text_questions
    resources :dictation_questions
    resources :multiple_choice_questions    
  end
  
  resources :users do
    resources :statistics
    resources :practice_entries
  end
  
  resources :tags
  
  root :to => "home#index"
  match '/quizzes/tags/:tag' => "quizzes#index", :as => :quiz_tag
  match '/quizzes/:id/reassign' => "quizzes#reassign", :as => :reassign_question
  match '/questions/:id/edit' => "questions#edit", :as => :edit_question  
  match "/multiple_choice_questions/:id" => "multiple_choice_questions#show", :as => :multiple_choice_question, :via => :get
  match "/multiple_choice_questions/:id" => "multiple_choice_questions#update", :via => :put
  match 'statistics' => "statistics#create"
  match '/quizzes/:id/take' => "quizzes#take", :as => :take
  match "/quizzes/:quiz_id/questions/new" => "patients#show"
  match "/images/uploads/*path" => "gridfs#serve"
  
  resources :practice_entries
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :take, Quiz
    can :show, Quiz
    if user
      can :manage, Statistic, :user_id => user.id
      can :create, PracticeEntry
      can :manage, PracticeEntry, :user_id => user.id
      can :manage, :all if user.admin?
    end
  end
end

app/models/choice.rb
class Choice
  include Mongoid::Document

  field :question
  field :correct, :type => Boolean, :default => false

  validates_presence_of :question
  
  embedded_in :answerable, :polymorphic => true
end

app/models/dictation_question.rb
class DictationQuestion < Question
  field :answer
  
  validates_presence_of :answer
  validates_presence_of :audio

  def type
    "Dictation"
  end
end

app/models/practice_entry.rb
class PracticeEntry
  include Mongoid::Document
  
  belongs_to :user
  validates_presence_of :hours, :date
  field :hours, :tyoe => BigDecimal
  field :date, :type => Date
  
end

app/models/question.rb
require 'carrierwave/orm/mongoid'
class Question
  #Question type constants
  MULTIPLE_CHOICE = "MultipleChoiceQuestion"
  DICTATION = "DictationQuestion"
  TEXT = "TextQuestion"
  VALID_TYPES = [MULTIPLE_CHOICE, DICTATION, TEXT]
  
  include Mongoid::Document
  include Mongoid::Timestamps

  validates_presence_of :title

  default_scope asc(:created_at)
  before_save :store_lowercase_title
  field :title
  field :lowercase_title
  belongs_to :quiz
  mount_uploader :audio, AudioUploader
  mount_uploader :image, ImageUploader
  def store_lowercase_title
    self.lowercase_title = title.downcase
  end
end

app/models/quiz.rb
class Quiz
  include Mongoid::Document
  include Mongoid::Timestamps

  default_scope asc(:lowercase_title)
  validates_presence_of :title
  validates_presence_of :number, :if => :persisted?
  before_create :generate_number
  before_save :store_lowercase_title

  field :title
  field :lowercase_title
  #integer unique identifier
  field :number, :type => Integer
  index :number

  has_many :questions
  has_many :tags, :as => :taggable

  def store_lowercase_title
    self.lowercase_title = title.downcase
  end

  def number= number
    write_attribute(:number, number)
  end

  def generate_number
    last_quiz_number = Quiz.max(:number).to_i
    self.number = last_quiz_number ? (last_quiz_number + 1) : 1
  end
  def has_tag?(name)
    tags.where(:name => name).count > 0
  end
  def self.tag_search(search)
    if search
      Quiz.all.collect { |quiz| quiz if quiz.has_tag?(search) }.compact      
    else
      scoped
    end
  end

end

app/models/statistic.rb
class Statistic
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :user
  belongs_to :quiz
  default_scope desc(:created_at)

  field :percent, :type => Integer
  field :questions_right, :type => Integer
  field :questions_wrong, :type => Integer
  
  validates_presence_of :percent, :questions_right, :questions_wrong
end

app/models/tag.rb
class Tag
  include Mongoid::Document
  field :name
  field :type
  index :type
  before_create :save_type
  validates_presence_of :name
  belongs_to :taggable, :polymorphic => :true
  def save_type
    self.type = taggable.class.to_s.downcase
  end
end

app/models/text_question.rb
class TextQuestion < Question
  field :answer

  validates_presence_of :answer


  def type
    "Freeform"
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

  field :admin, :type => Boolean, :default => false
  field :full_name
  has_many :statistics
  has_many :practice_entries
  validates_presence_of :full_name

  def average_score
    if(statistics.count > 0)
      percent_sum = 0
      statistics.select {|statistic| percent_sum += statistic.percent }
      (percent_sum/statistics.count).to_i
    else
      100
    end
  end
  def total_questions_answered
    answered = 0
    statistics.select {|statistic| answered += statistic.questions_right + statistic.questions_wrong}
    answered
  end
  def total_questions_right
    answered = 0
    statistics.select {|statistic| answered += statistic.questions_right }
    answered
  end
  def total_questions_wrong
    answered = 0
    statistics.select {|statistic| answered += statistic.questions_wrong }
    answered
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  def index
    
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  respond_to :html
  inherit_resources
  actions :delete, :destroy
  def index
    
  end
  def destroy
    @tag = Tag.find(params[:id])
    @tag.delete
    respond_with(@tag) do |format|
      format.html { render :layout => !request.xhr? }
    end
    #destroy! { :layout => false }
  end
  def create
    # Grab parent that holds tags
    @taggable = params[:taggable_type].constantize.find(params[:taggable_id])
    # Create tag from params
    @tag = Tag.new(params[:tag])
    # Persist, will not persist if tag is not valid
    @taggable.tags << @tag    
    respond_with(@tag) do |format|
      format.html { render :layout => !request.xhr? }
    end
  end    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def readable_date(date)
    date.strftime("%d %B %Y")
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def fabricate_question_from_type(q_type)
    if q_type == Question::DICTATION
      return DictationQuestion.new
    end
    if q_type == Question::MULTIPLE_CHOICE
      return MultipleChoiceQuestion.new
    end
    nil
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title English Quiz Administration
    = stylesheet_link_tag :flutie, 'main'
    = javascript_include_tag :defaults
    = javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js'
    = javascript_include_tag 'flash'
    
    -# Raphael Includes
    = javascript_include_tag 'raphael.js'
    = javascript_include_tag 'http://g.raphaeljs.com/g.raphael.js'
    = javascript_include_tag 'http://g.raphaeljs.com/g.pie.js'    
    
    -# Lazy High Charts
    = javascript_include_tag :high_charts

    
    = csrf_meta_tag
    :plain
      <link  href="http://fonts.googleapis.com/css?family=Ubuntu:regular,italic,bold,bolditalic" rel="stylesheet" type="text/css" >
  %body
    #menu
      = link_to "Home", root_path      
      - if current_user
        = link_to "My Statistics", user_statistics_url(current_user)
        = link_to "Practice Entries", user_practice_entries_url(current_user)
        - if current_user.admin?
          = link_to "Manage Users", users_url
          = link_to "Manage Quizzes", quizzes_url
                
        = link_to "Edit Profile", edit_user_registration_url(current_user)

        = link_to "Log out", destroy_user_session_url(current_user)
    %div
      - if notice
        #main_notice.notice= notice
      - if alert
        #main_error.error= alert

    = yield

app/views/shared/_admin_question_row.html.haml
%tr
  %td{:style => "width: 40px; padding: 0px;"}= check_box_tag "assignees[]", question.id if current_user.admin?
  %td.title= (question_counter+1).to_s + ". " + question.title
  - unless question.audio.url.blank?
    %td= link_to "Open", question.audio.url, :target => "_blank"
  - else
    %td No Audio
  - unless question.image.url.blank?
    %td= link_to "Open", question.image.url, :target => "_blank"
  - else
    %td No Image
    
  %td= question.type
  %td
    - if current_user.admin?
      = link_to "edit", edit_question_path(question)
      |
      = link_to "delete", quiz_question_path(question.quiz,question), :method => :delete
  

- if question.class == MultipleChoiceQuestion
  - question.choices.each_with_index do |choice, index|
    - sub_class = ((index+1) == question.choices.count) ? 'sub' : 'last_sub'
    %tr
      %td{:class => sub_class}
      %td{:class => sub_class, :colspan => "5"} #{choice.question} | #{choice.correct}

app/views/shared/_error_messages.html.haml
- if target.errors.any?
  #errorExplanation.error
    %h4 #{pluralize(target.errors.count, "error")} prohibited this record from being saved:
    %ul
      - target.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_question_row.html.haml
%tr
  %td.title= (question_counter+1).to_s + ". " + question.title

  - unless question.audio.url.blank?
    %td= link_to "Open", question.audio.url, :target => "_blank"
  - else
    %td No Audio
  - unless question.image.url.blank?
    %td= link_to "Open", question.image.url, :target => "_blank"
  - else
    %td No Image
    
  %td= question.type
  %td
    = link_to "edit", edit_question_path(question)
    |
    = link_to "delete", quiz_question_path(question.quiz,question), :method => :delete
  

- if question.class == MultipleChoiceQuestion
  - question.choices.each_with_index do |choice, index|
    - sub_class = ((index+1) == question.choices.count) ? 'sub' : 'last_sub'
    %tr
      %td{:class => sub_class, :colspan => "4"} #{choice.question} | #{choice.correct}

app/views/shared/_quiz_row.html.haml
%tr
  %td.title= (quiz_counter+1).to_s + ". " + quiz.title
  %td= quiz.questions.count
  %td
    = link_to "Show", quiz_url(quiz)
    |
    = link_to "Take Quiz", take_url(quiz)
    - if current_user.admin?
      |
      = link_to "Edit", edit_quiz_url(quiz)
  %td= quiz.number